version: '3.8'

services:
  # Frontend do jogo
  web:
    build:
      # Buscando direto do repositório de código do frontend
      context: https://github.com/solero/wand-web.git#master
    environment:
      - LOGIN_IP=${LOGIN_IP}
      - LOGIN_PORT=${LOGIN_PORT}
      - WORLD_PORT=${WORLD_PORT}
      - MEDIA_URL=${MEDIA_URL}
    restart: always

  # Servidor de mídia (Imagens)
  media:
    build:
      # Buscando direto do repositório que contém as imagens
      context: https://github.com/solero/vanilla-media.git#master
    restart: always

networks:
  coolify:
    external: true
