version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - LOGIN_IP=${LOGIN_IP}
      - LOGIN_PORT=${LOGIN_PORT}
      - WORLD_PORT=${WORLD_PORT}
      - MEDIA_URL=${MEDIA_URL}
    restart: always

  media:
    build:
      context: .
      dockerfile: vanilla-media/Dockerfile
    restart: always

networks:
  coolify:
    external: true
