version: '3.8'

services:
  # Frontend do jogo
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - LOGIN_IP=${LOGIN_IP}
      - LOGIN_PORT=${LOGIN_PORT}
      - WORLD_PORT=${WORLD_PORT}
      - MEDIA_URL=${MEDIA_URL}
    networks:
      - coolify

  # Servidor de mídia (ajuste o caminho se necessário)
  media:
    image: nginx:alpine
    volumes:
      - ./vanilla-media:/usr/share/nginx/html/media
    networks:
      - coolify

networks:
  coolify:
    external: true
